### ISSUE TITLE
Provide shortcuts for reading mode

### ISSUE THREAD

**Issue by Mno-hime** [yegortimoshenko/paper#13]
When I am done with an article in read mode (e.g. https://www.instapaper.com/read/123456), I'd love to have the possibility to mark the article with a keyboard shortcut.

I'd suggest following defaults: [A] for archive, [L] to like it, [DEL] or [D] to delete it; lowercase should work as well. (Thanks for excellent addon.)

**Comment by yegortimoshenko** [comment]
Done. I've mapped it this way:

Hotkey | Action
------------- | -------------
j  | Scroll down
k | Scroll up
a | Archive
l | Like
d | Delete

Please try beta release that includes this feature and tell me what you think:

http://yegortimoshenko.com/downloads/paper.xpi

Other improvements included in the beta release:

+ button for hotkey assignment #11 
+ locales (currently only ru-RU and en-US) #8 
+ updated text in preferences #10 
+ bug fix: password and username are now escaped #4 

The full-featured release will land Mozilla Addons in about half a month, but after you switch to the beta version you won't get automatic updates. I'll ping you back in this issue when the release is ready so you will switch to the release branch that includes automatic updates.

**Comment by Mno-hime** [comment]
Thank You for the feature!

I'd love to test but I got "403 Forbidden OpenBSD httpd" when downloading the XPI.

**Comment by yegortimoshenko** [comment]
@Mno-hime Oh, damn, sorry. Fixed.

**Comment by Mno-hime** [comment]
Archive, Like, and Delete work as expected. Thanks! Unfortunately now I am unable to use `ArrowUp` and `ArrowDown` on keyboard since`j` and `k` occupy their place.

**Comment by yegortimoshenko** [comment]
Fixed in 383fa65f87bdbb542bc0cc6bb5f1dfda7929a0ac, now arrow keys should work as expected, as well as `PageUp`, `PageDown` et cetera. Updated version is under the same address:

http://yegortimoshenko.com/downloads/paper.xpi

**Comment by Mno-hime** [comment]
Now Arrows and co. work as expected. Thanks. However, I noticed `j` and `k` scroll twice of what `ArrowUp` and `ArrowDown` does. `j` and `k` seem to be set to 100, but Arrows scroll about 50. Also, scrolling via `k` and `j` does not take into consideration smooth scrolling I have enabled.

**Comment by yegortimoshenko** [comment]
There's no any viable API to smooth scroll in Firefox. I will calibrate the scrolling distance, though, and will ping you back once it's settled.

**Comment by yegortimoshenko** [comment]
Yet another beta (1.0.0-beta3) is ready, now j/k scroll exactly as much as arrow keys:

http://yegortimoshenko.com/downloads/paper.xpi

It also includes updated icons and some refactoring.

**Comment by Mno-hime** [comment]
> There's no any viable API to smooth scroll in Firefox.

I found this: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior. Though, not sure whether it applies to addons.

Tested Beta3's `j`/`k` functionality, looks good to me, thou I probably won't use it.

**Comment by yegortimoshenko** [comment]
It is inapplicable, unfortunately. Maybe I could emulate smooth scrolling using JavaScript, and check internal Firefox settings to see if it is on or off, but I'll track it in #19.
