### ISSUE TITLE
Store password in Firefox Password Manager (sdk/passwords module)

### ISSUE THREAD

**Issue by yegortimoshenko** [yegortimoshenko/paper#15]
I could switch the clear password field to a button that opens a pop-up with a password type field.
Then I could store this password in Password Manager, which, as I remember, can be optionally encrypted.

**Comment by yegortimoshenko** [comment]
Also see #18 for insight by @Mno-hime (thank you a lot!). Have to check this Zotero addon.

**Comment by Mno-hime** [comment]
I am wondering if Paper needs to handle username and password at all. Just installed Instapaper's official Chrome extension and it does not require username/password, it just forwards me to instapaper.com to log in. I guess it just uses similar code to what is in bookmarklet for Firefox (https://www.instapaper.com/save).

Perhaps username/password may be handled by Paper only optionally. Then if I wasn't logged in to instapaper.com and I did not provide username/password to Paper, Paper would just forward me to log in to instapaper.com and then instapaper.com would automatically added the page.

**Comment by yegortimoshenko** [comment]
@Mno-hime I'll have to switch to full Instapaper API and receive an access token for this addon to enable that feature, which is a hassle (see [#1](https://github.com/yegortimoshenko/paper/issues/1#issuecomment-126894096)).

Using `sdk/passwords` is a minor improvement over what is here now, and, frankly, it is `SimplePrefs` fault that they don't have a `password` type. It will mean I'll have to make a button that opens a pop-up for entering your credentials. I don't want to make anyone do that, so yeah, I'll wait for Instapaper reply on #1 and then decide whether I leave password entry as it is now or make an automatic authorization like in official Instapaper addon for Chrome.

Thank you for your suggestion, I've forgot that you can do the same thing with a bookmarking addon, not just web applications.
