### ISSUE TITLE
New toolbar icon

### ISSUE THREAD

**Issue by Mno-hime** [yegortimoshenko/paper#16]
I think the toolbar icon (the capital "I") is a bit narrow and does not match closely the "I" from official Instapaper favicon logo.

Old: ![old](https://cloud.githubusercontent.com/assets/4632197/9026602/d5100ae2-3935-11e5-9920-528cc5e8fb3c.png)

New: ![new](https://cloud.githubusercontent.com/assets/4632197/9026604/dd448c2e-3935-11e5-8fe0-44ca2bd35809.png)
Also changed color to match the color in the official logo.

Here:  ![default](https://cloud.githubusercontent.com/assets/4632197/9026642/b9f79be8-3936-11e5-8458-000a3e785db6.png)

**Comment by yegortimoshenko** [comment]
Related: #2

**Comment by yegortimoshenko** [comment]
Check this one out:

![default-16](https://cloud.githubusercontent.com/assets/1643293/9027721/9fa72ea8-3971-11e5-9d7f-ca8998204d4f.png)

Here's how it looks like in action:

![screen shot 2015-08-02 at 23 51 59](https://cloud.githubusercontent.com/assets/1643293/9027720/8872e8e4-3971-11e5-8206-d6c112efc233.png)

Perfectly aligned with built-in Firefox icons:

![screen shot 2015-08-03 at 00 10 24](https://cloud.githubusercontent.com/assets/1643293/9027807/4f20bb04-3974-11e5-9eac-4dc9281b62fd.png)

![screen shot 2015-08-03 at 00 11 45](https://cloud.githubusercontent.com/assets/1643293/9027810/638025a8-3974-11e5-8f82-5e8cd0ec6076.png)

Colors are exactly the same as in built-in icons (R: 77 G:77 B:77).

What do you think?

**Comment by yegortimoshenko** [comment]
Also see the new addon icon:

Before | After
---------|--------
![Old icon](https://cloud.githubusercontent.com/assets/1643293/9027975/427444ec-397a-11e5-868a-39b830d9d511.png) | ![icon](https://cloud.githubusercontent.com/assets/1643293/9027976/561019e0-397a-11e5-935d-c57228c0df76.png)

**Comment by Mno-hime** [comment]
Both look great to me. Makes sense to have the toolbar icon aligned with the rest.

**Comment by yegortimoshenko** [comment]
I'll close this for now: feel free to reopen it. I'll track 32px and 64px icons in #2.
