### ISSUE TITLE
Paper should use Password Manager

### ISSUE THREAD

**Issue by Mno-hime** [yegortimoshenko/paper#18]
I am not sure this is possible but Paper should use the Password Manager in Firefox instead of holding the password on its own. I can see that Zotero addon has an entry in the Password Manager: `chrome://zotero`. Also Paper should use "password" input field in its Settings so the password is not to be seen that easily.

**Comment by yegortimoshenko** [comment]
Will do. Closing for now as a duplicate of #15.
