### ISSUE TITLE
Shortcuts should be disabled when adding notes

### ISSUE THREAD

**Issue by Mno-hime** [yegortimoshenko/paper#20]
It's not possible to use keys which were assigned as shotcuts recently (`A`, `L`, `S`; and is somewhat possible with `J` and `K`). E.g. instead of 'A' being inserted to the note, page is Archived.

**Comment by yegortimoshenko** [comment]
Done. Here is a fixed version:

https://yegortimoshenko.com/downloads/paper-v1.0.0-beta5.xpi

**Comment by Mno-hime** [comment]
Verified it's fixed. Thanks! (I noticed I need to restart Firefox before the fixed version of Paper kicks in but Addon Manager does not ask me to restart Firefox after update.)
