### ISSUE TITLE
Provide shortcut for "Save to Instapaper" in Text Mode

### ISSUE THREAD

**Issue by Mno-hime** [yegortimoshenko/paper#21]
Please, provide shortcut (I'd suggest `S`) for "Save to Instapaper" in Text Mode at: https://www.instapaper.com/text?u=http%3A%2F%2Fwww.blisty.cz%2Fart%2F78382.html.

**Comment by yegortimoshenko** [comment]
Check https://yegortimoshenko.com/downloads/paper-v1.0.0-beta6.xpi for a new beta that includes this feature.
